#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Domotica.Resource", IsApplication=true)]

namespace Domotica
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int PhoneBack = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int PhoneBackground = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060023
			public const int abort = 2131099683;
			
			// aapt resource value: 0x7f060009
			public const int buttonConnect = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int buttonOnOff1 = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int buttonOnOff2 = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int buttonOnOff3 = 2131099671;
			
			// aapt resource value: 0x7f06001e
			public const int buttonSwitch1 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int buttonSwitch2 = 2131099679;
			
			// aapt resource value: 0x7f060012
			public const int buttonToggle1 = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int buttonToggle2 = 2131099670;
			
			// aapt resource value: 0x7f06001c
			public const int buttonToggle3 = 2131099676;
			
			// aapt resource value: 0x7f060007
			public const int editTextIPAddress = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int editTextIPPort = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int editTextThreshold1 = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int editTextThreshold2 = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int editTextThreshold3 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int editTextThreshold4 = 2131099675;
			
			// aapt resource value: 0x7f060021
			public const int editTextTimerSpeed = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int exit = 2131099682;
			
			// aapt resource value: 0x7f06000a
			public const int gridLayout1 = 2131099658;
			
			// aapt resource value: 0x7f060019
			public const int linearLayout1 = 2131099673;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout2 = 2131099677;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int textViewIPAddress = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int textViewIPPort = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int textViewOnOff = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int textViewServer = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int textViewServerConnect = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int textViewThreshold = 2131099661;
			
			// aapt resource value: 0x7f060020
			public const int textViewTimerSpeedText = 2131099680;
			
			// aapt resource value: 0x7f060001
			public const int textViewTimerState = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int textViewTimerStateValue = 2131099650;
			
			// aapt resource value: 0x7f06000e
			public const int textViewToggle = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int textViewValue = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int textViewValue1 = 2131099664;
			
			// aapt resource value: 0x7f060014
			public const int textViewValue2 = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int textViewValue3 = 2131099672;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040029
			public const int abort = 2130968617;
			
			// aapt resource value: 0x7f040000
			public const int application_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int arduino_server_connect = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int arduino_server_text = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int button_connect_text = 2130968585;
			
			// aapt resource value: 0x7f040021
			public const int button_pin_state_colour = 2130968609;
			
			// aapt resource value: 0x7f040012
			public const int button_pin_state_text1 = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int button_pin_state_text2 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int button_pin_state_text3 = 2130968596;
			
			// aapt resource value: 0x7f04001c
			public const int button_switch_state1 = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int button_switch_state2 = 2130968605;
			
			// aapt resource value: 0x7f040023
			public const int change_pin_state_value = 2130968611;
			
			// aapt resource value: 0x7f040026
			public const int debug_text = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int debug_value = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int exit = 2130968616;
			
			// aapt resource value: 0x7f040005
			public const int ip_address_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ip_address_value = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ip_port_text = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ip_port_value = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int on_off_text = 2130968586;
			
			// aapt resource value: 0x7f040022
			public const int pin_state_text = 2130968610;
			
			// aapt resource value: 0x7f040024
			public const int sensor_text = 2130968612;
			
			// aapt resource value: 0x7f040015
			public const int sensor_text1 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int sensor_text2 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int sensor_text3 = 2130968599;
			
			// aapt resource value: 0x7f040025
			public const int sensor_value = 2130968613;
			
			// aapt resource value: 0x7f040018
			public const int threshold_input1 = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int threshold_input2 = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int threshold_input3 = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int threshold_input4 = 2130968603;
			
			// aapt resource value: 0x7f04000e
			public const int threshold_text1 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int threshold_text2 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int threshold_text3 = 2130968592;
			
			// aapt resource value: 0x7f04001f
			public const int timer_speed = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int timer_speed_text = 2130968606;
			
			// aapt resource value: 0x7f040001
			public const int timer_state_text = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int timer_state_value = 2130968578;
			
			// aapt resource value: 0x7f040011
			public const int toggle_text = 2130968593;
			
			// aapt resource value: 0x7f04000b
			public const int value_text1 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int value_text2 = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int value_text3 = 2130968589;
			
			// aapt resource value: 0x7f040020
			public const int value_value_text = 2130968608;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
